# Generated by Django 5.0.2 on 2024-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_remove_playlist_musics_remove_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_genre',
            field=models.CharField(null='True'),
            preserve_default='True',
        ),
    ]
