# Generated by Django 5.0.2 on 2024-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_mood',
            field=models.CharField(null='True'),
            preserve_default='True',
        ),
    ]
